version: 0.2

phases:
  pre_build:
    commands:
      - cd frontend
      - npx yarn
      - yarn test:ci
  build:
    commands:
      - npx yarn build
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build

cache:
  paths:
    - /root/.npm/**/*
