version: 0.2
phases:
  install:
    commands:
      - cd backend
      - npm i -g serverless
      - npm i
  #  pre_build:
  #    commands:
  #      - npm run test
  build:
    commands:
      - serverless deploy
cache:
  paths:
    - /root/.npm/**/*
