# org: serverlessinc
# app: aws-node-rest-api
service: swz-news-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: prd

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
