# org: serverlessinc
# app: aws-node-rest-api
service: swz-news-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: prd
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: ${DEPLOYMENT_BUCKET}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
