version: 0.2

phases:
  build:
    commands:
      - if [ -z $TERRAFORM_DIRECTORY] then cd $TERRAFORM_DIRECTORY; fi
      - terraform init -input=false
      - terraform workspace select $TERRAFORM_WORKSPACE
      - terraform validate
      - terraform plan -input=false
artifacts:
  files:
    - '**/*'
